export const VOLLEY_MGT_GET_SOGGETTI_BEGIN = 'VOLLEY_MGT_GET_SOGGETTI_BEGIN';
export const VOLLEY_MGT_GET_SOGGETTI_SUCCESS = 'VOLLEY_MGT_GET_SOGGETTI_SUCCESS';
export const VOLLEY_MGT_GET_SOGGETTI_FAILURE = 'VOLLEY_MGT_GET_SOGGETTI_FAILURE';
export const VOLLEY_MGT_GET_SOGGETTI_DISMISS_ERROR = 'VOLLEY_MGT_GET_SOGGETTI_DISMISS_ERROR';
export const VOLLEY_MGT_COUNTER_PLUS_ONE = 'VOLLEY_MGT_COUNTER_PLUS_ONE';
export const VOLLEY_MGT_COUNTER_MINUS_ONE = 'VOLLEY_MGT_COUNTER_MINUS_ONE';
